package _02_exception;

import java.util.InputMismatchException;
import java.util.Scanner;

public class T11_Exception {

	public static void main(String[] args) {
		
		
		/*	
			try {
			int[] num = new int[3];
			Scanner sc = new Scanner(System.in);
			System.out.println("정수 입력 ");
			
			int sum = 0;
			
			for(int i =0; i<num.length; i++) {
				System.out.println(i+1 + "번째 정수 입력 : ");
				num[i] = sc.nextInt();
				sum += num[i];
			}
			
			num[3] = 5;
			System.out.println("합계" + sum);
		
			}catch(ArrayIndexOutOfBoundsException e) {
				System.out.println("배열의 범위를 넘어섰어요!");
				
			}catch(InputMismatchException e) {
				System.out.println("정수만 넣으세요.");
			★	★	★	★	★	★	★	★	★	★	★	★	★	★	★	★	
				// ★ Exception 을 쓸때 주의점 : 맨위에다가 쓸 수 없음 . 맨 아래에다가 적어야함.
			}catch(Exception e) { // Exception : 모든 예외 클래스의 최상위 클래스, 모든 예외를 다 받을 수 있음
				System.out.println("예외발생");
				e.printStackTrace(); // 몇번째 줄에 exception이 나왔는지 다 알려줌 
				
				// System.out.println(e); ▶ 얘는 그냥 exception 나왔다고 말해줌
				
				}
			*/
		
		
		
			
	}

}
